<?php
$quartiers = array(
    "Aeroport international leon mba",
    "Akemindjogoni",
    "Akournam",
    "Akébé kinguélé",
    "Akébé plaine",
    "Akébé ville",
    "Alibandeng",
    "Anbowe",
    "Angondjé",
    "Angoungou",
    "Atong-abé",
    "Avorbam",
    "Avéa",
    "Awendjé",
    "Barracuda",
    "Bas de Gué Gué",
    "Batterie IV",
    "Beau-Séjour",
    "Bel air",
    "Bellevue",
    "Bibéré",
    "Bissegué",
    "Bissobinam",
    "Bizango rail",
    "Bizango-Bibéré",
    "Camp de gaulle",
    "Cap estarias",
    "Cité damas",
    "Cité de la Démocratie",
    "Cocotier",
    "Dakar",
    "Derrière la Prison",
    "Dibadiba",
    "Dieu seul",
    "Glass",
    "Grand village",
    "Gros bouquet",
    "Hauts de Gué Gué",
    "Igoumie",
    "Kalikak",
    "La Peyrie",
    "La Sorbonne",
    "Lalala à droite",
    "Lalalaa à gauche",
    "Likouala",
    "London ",
    "Louis",
    "Mikolongo",
    "Mindoumbé",
    "Mont Bouet",
    "Montagne Sainte",
    "Mélen",
    "Ngindabato",
    "Nkembo",
    "Nkok",
    "Nkol ogoum",
    "Nomabakélé",
    "Nomba",
    "Nzeng–Ayong",
    "Nzog-mitang",
    "Nzogobeyok",
    "Okala",
    "Oloumi",
    "Ondongo",
    "Owendo",
    "Ozangué",
    "PK1",
    "PK10",
    "PK11",
    "PK12",
    "PK13",
    "PK14",
    "PK15",
    "PK2",
    "PK3",
    "PK5",
    "PK6",
    "PK7",
    "PK8",
    "PK9",
    "Petit Paris",
    "Petit Village",
    "Plaine Niger",
    "Plaine Oréty",
    "Pont Nomba",
    "Pont de Gué Gué",
    "STFO",
    "Sibang",
    "Sotéga",
    "Tahiti",
    "Terre Nouvelle",
    "Toulon",
    "Vallée Ste-Marie",
    "Vallée Ste-Marie SDV",
    "Venez-Voir",
    "Zone Industielle Oloumi Nord",
    "Zone Industielle Oloumi Sud",
    "Zone Oprag Alénakiri",
    "îls Agoumé",
    "îls Conniquet",
    "îls Perroquet",
    "îls Pointe Denis"
);
echo json_encode($quartiers);
?>


